### ISSUE TITLE
Remove words from "hidden anagrams" that aren't actually anagrams

### ISSUE THREAD

**Issue by boisvert42** [adamaaronson/wordlisted#3]
For instance, if I search hidden anagrams for "WATER" something like WATERTIGHT shouldn't show up, ideally.

**Comment by adamaaronson** [comment]
I think this is already fixed, WATERTIGHT doesn't show up when I search WATER with the English dictionary. Some bogus ones show up, like FIREWATER which technically contains REWAT as a WATER anagram. But if a word only contains WATER in order then it won't show up.

**Comment by boisvert42** [comment]
Maybe I gave a bad example then, but what do you think about removing results like FIREWATER?
